# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb:10.1.48
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:ro
    restart: always
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    